# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.27
# 

Name:       wayland

# >> macros
# << macros

Summary:    Wayland Compositor Infrastructure
Version:    1.5.0
Release:    1
Group:      System/Libraries
License:    MIT
URL:        http://wayland.freedesktop.org/
Source0:    wayland-%{version}.tar.xz
Source100:  wayland.yaml
BuildRequires:  pkgconfig(expat)
BuildRequires:  pkgconfig(libffi)

%description
Wayland is a protocol for a compositor to talk to its clients as well as a C
library implementation of that protocol. The compositor can be a standalone
display server running on Linux kernel modesetting and evdev input devices,
an X application, or a wayland client itself. The clients can be traditional
applications, X servers (rootless or fullscreen) or other display servers.


%package devel
Summary:    Common headers for wayland
Group:      Development/Libraries
Requires:   %{name} = %{version}-%{release}

%description devel
Common headers for wayland.

%package -n libwayland-client
Summary:    Wayland client library
Group:      Development/Libraries
Requires:   %{name} = %{version}-%{release}
Requires(post): /sbin/ldconfig
Requires(postun): /sbin/ldconfig

%description -n libwayland-client
Wayland client library.

%package -n libwayland-client-devel
Summary:    Headers and symlinks for developing wayland client applications
Group:      Development/Libraries
Requires:   %{name} = %{version}-%{release}
Requires:   libwayland-client = %{version}-%{release}

%description -n libwayland-client-devel
Headers and symlinks for developing wayland client applications.

%package -n libwayland-cursor
Summary:    Wayland cursor library
Group:      Development/Libraries
Requires:   %{name} = %{version}-%{release}
Requires(post): /sbin/ldconfig
Requires(postun): /sbin/ldconfig

%description -n libwayland-cursor
Wayland cursor library.

%package -n libwayland-cursor-devel
Summary:    Headers and symlinks for developing wayland cursor applications
Group:      Development/Libraries
Requires:   %{name} = %{version}-%{release}
Requires:   libwayland-cursor = %{version}-%{release}

%description -n libwayland-cursor-devel
Headers and symlinks for developing wayland cursor applications.

%package -n libwayland-server
Summary:    Wayland server library
Group:      Development/Libraries
Requires:   %{name} = %{version}-%{release}
Requires(post): /sbin/ldconfig
Requires(postun): /sbin/ldconfig

%description -n libwayland-server
Wayland server library.

%package -n libwayland-server-devel
Summary:    Headers and symlinks for developing wayland server applications
Group:      Development/Libraries
Requires:   %{name} = %{version}-%{release}
Requires:   libwayland-server = %{version}-%{release}

%description -n libwayland-server-devel
Headers and symlinks for developing wayland server applications.

%prep
%setup -q -n %{name}-%{version}/wayland

# >> setup
# << setup

%build
# >> build pre
# << build pre

%reconfigure --disable-static \
    --disable-documentation

make %{?_smp_mflags}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post

# << install post

%post -n libwayland-client -p /sbin/ldconfig

%postun -n libwayland-client -p /sbin/ldconfig

%post -n libwayland-cursor -p /sbin/ldconfig

%postun -n libwayland-cursor -p /sbin/ldconfig

%post -n libwayland-server -p /sbin/ldconfig

%postun -n libwayland-server -p /sbin/ldconfig

%files
%defattr(-,root,root,-)
%doc README TODO
# >> files
# << files

%files devel
%defattr(-,root,root,-)
%{_bindir}/wayland-scanner
%{_includedir}/wayland-util.h
%{_includedir}/wayland-egl.h
%{_includedir}/wayland-version.h
%{_datadir}/aclocal/wayland-scanner.m4
%{_libdir}/pkgconfig/wayland-scanner.pc
%dir %{_datadir}/wayland
%{_datadir}/wayland/wayland-scanner.mk
%{_datadir}/wayland/wayland.xml
%{_datadir}/wayland/wayland.dtd
%{_mandir}/man3/*.3*
# >> files devel
# << files devel

%files -n libwayland-client
%defattr(-,root,root,-)
%{_libdir}/libwayland-client.so.0*
# >> files libwayland-client
# << files libwayland-client

%files -n libwayland-client-devel
%defattr(-,root,root,-)
%{_includedir}/wayland-client*.h
%{_libdir}/libwayland-client.so
%{_libdir}/pkgconfig/wayland-client.pc
# >> files libwayland-client-devel
# << files libwayland-client-devel

%files -n libwayland-cursor
%defattr(-,root,root,-)
%{_libdir}/libwayland-cursor.so.0*
# >> files libwayland-cursor
# << files libwayland-cursor

%files -n libwayland-cursor-devel
%defattr(-,root,root,-)
%{_includedir}/wayland-cursor*.h
%{_libdir}/libwayland-cursor.so
%{_libdir}/pkgconfig/wayland-cursor.pc
# >> files libwayland-cursor-devel
# << files libwayland-cursor-devel

%files -n libwayland-server
%defattr(-,root,root,-)
%{_libdir}/libwayland-server.so.0*
# >> files libwayland-server
# << files libwayland-server

%files -n libwayland-server-devel
%defattr(-,root,root,-)
%{_includedir}/wayland-server*.h
%{_libdir}/libwayland-server.so
%{_libdir}/pkgconfig/wayland-server.pc
# >> files libwayland-server-devel
# << files libwayland-server-devel
